schedule: "0 * * * *"  # Esegui ogni ora
image:
  repository: "python"
  tag: "3.9-slim"
  pullPolicy: "IfNotPresent"
script: "print('Hello from test environment')"  # Script Python eseguito per test
restartPolicy: "OnFailure"

resources:
  limits:
    cpu: "300m"
    memory: "192Mi"
  requests:
    cpu: "150m"
    memory: "96Mi"
