schedule: "0 0 * * *"
image:
  repository: "python"
  tag: "3.9-slim"
  pullPolicy: "IfNotPresent"
script: "print('Hello from default environment')"
restartPolicy: "OnFailure"

resources:
  limits:
    cpu: "500m"
    memory: "256Mi"
  requests:
    cpu: "250m"
    memory: "128Mi"
