schedule: "*/5 * * * *"  # Esegui ogni 5 minuti
image:
  repository: "python"
  tag: "3.9-slim"
  pullPolicy: "Always"
script: "print('Hello from development environment')"  # Script Python eseguito per dev
restartPolicy: "OnFailure"

resources:
  limits:
    cpu: "200m"
    memory: "128Mi"
  requests:
    cpu: "100m"
    memory: "64Mi"
